// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8h_hPl07aCqpVBhto14QHgfhJE2AtqNQ',
    appId: '1:164244313415:web:4256376c790ccc1ed4a862',
    messagingSenderId: '164244313415',
    projectId: 'project-ral069',
    authDomain: 'project-ral069.firebaseapp.com',
    storageBucket: 'project-ral069.appspot.com',
    measurementId: 'G-7LQTQY61JQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPb5D-MQIfuJigJTJow5P0RmsSR4YGPYo',
    appId: '1:164244313415:android:9724c8fc8cb3dd4cd4a862',
    messagingSenderId: '164244313415',
    projectId: 'project-ral069',
    storageBucket: 'project-ral069.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhnJ9J4fyBjVSNApweHqVcfa4VR5uXMDA',
    appId: '1:164244313415:ios:ebb51dd4bbb450f9d4a862',
    messagingSenderId: '164244313415',
    projectId: 'project-ral069',
    storageBucket: 'project-ral069.appspot.com',
    iosClientId: '164244313415-di99ogvnrnppmg7rktgtu46r959flhf1.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhnJ9J4fyBjVSNApweHqVcfa4VR5uXMDA',
    appId: '1:164244313415:ios:ebb51dd4bbb450f9d4a862',
    messagingSenderId: '164244313415',
    projectId: 'project-ral069',
    storageBucket: 'project-ral069.appspot.com',
    iosClientId: '164244313415-di99ogvnrnppmg7rktgtu46r959flhf1.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );
}
